# Generated by Django 4.2.6 on 2023-10-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("direccion", models.CharField(max_length=50, null=True)),
                ("tipoBar", models.CharField(max_length=50, null=True)),
                ("codigoPostal", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FacturaMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fechaFactura", models.DateField()),
                ("litrosEntregado", models.FloatField()),
                (
                    "idCliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="predictApp.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entregas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fechaPedido", models.DateField()),
                ("fechaEntrega", models.DateField()),
                ("litrosEntregados", models.IntegerField()),
                (
                    "idCliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="predictApp.cliente",
                    ),
                ),
            ],
        ),
    ]
