# This file is a template, and might need editing before it works on your project.
FROM python:3.9

WORKDIR /app



RUN pip install --upgrade pip

COPY ./requirements.txt requirements.txt

RUN pip install -r requirements.txt

# assignar permisos a ec2-user
COPY . .

EXPOSE 8080
CMD ["python", "manage.py", "runserver", "0.0.0.0:8080"]